/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author medaimane
 */
public class MainFrame extends javax.swing.JFrame {
    
    private OptionsFrame op;
    private AboutGameFrame abgf;

    private String playerImage;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.initComponents();
        this.init();
    }

    /**
     *
     * MY METHODES :
     *
     */
    private void init() {
        this.setLocationRelativeTo(null);
        this.setPanelDimension(this.homeGamePanel);
        this.setPanelDimension(this.homePanel);
        
        this.playerImage = "images/player1.jpg";

        this.setAddPictureLabel(this.player1jLabel, this.getResizedImage("images/player1.jpg", this.player1jLabel.getWidth(), this.player1jLabel.getHeight()));
        this.setAddPictureLabel(this.player2jLabel, this.getResizedImage("images/player2.jpg", this.player2jLabel.getWidth(), this.player2jLabel.getHeight()));
        this.setAddPictureLabel(this.player3jLabel, this.getResizedImage("images/player3.png", this.player3jLabel.getWidth(), this.player3jLabel.getHeight()));
        this.setAddPictureLabel(this.player4jLabel, this.getResizedImage("images/player4.png", this.player4jLabel.getWidth(), this.player4jLabel.getHeight()));
    }
    
    // Set text field the default Dimension :
    private void setPanelDimension(javax.swing.JPanel JP) {
        JP.setPreferredSize(new Dimension(JP.getWidth(), JP.getHeight()));
    }

    // resized image :
    // Set resized image for a lable  :
    private void setAddPictureLabel(javax.swing.JLabel label, Image image) {
        label.setIcon(new ImageIcon(resizeImage(
                new ImageIcon(image).getImage(),
                label.getWidth(),
                label.getHeight()
        )));
    }

    private Image resizeImage(Image img, int w, int h) {
        BufferedImage resizedImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2D = resizedImage.createGraphics();
        g2D.drawImage(img, 0, 0, w, h, null);
        g2D.dispose();

        return resizedImage;
    }
    // get image :
    private Image getResizedImage(String pathfile, int w, int h) {
        Image imguser = null;
        try {
            imguser = ImageIO.read(new File(pathfile));
        } catch (IOException ex) {
        }
        imguser = resizeImage(imguser, w, h);
        return imguser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        homeGamePanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        playGameButton = new javax.swing.JButton();
        aboutGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerNameTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        player1jLabel = new javax.swing.JLabel();
        player2jLabel = new javax.swing.JLabel();
        player3jLabel = new javax.swing.JLabel();
        player4jLabel = new javax.swing.JLabel();
        player1jRadioButton = new javax.swing.JRadioButton();
        player3jRadioButton = new javax.swing.JRadioButton();
        player2jRadioButton = new javax.swing.JRadioButton();
        player4jRadioButton = new javax.swing.JRadioButton();
        playerChoosedjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Menu");

        homeGamePanel.setBackground(new java.awt.Color(204, 204, 255));

        homePanel.setBackground(new java.awt.Color(153, 153, 255));

        playGameButton.setBackground(new java.awt.Color(51, 153, 255));
        playGameButton.setForeground(new java.awt.Color(255, 255, 255));
        playGameButton.setText("Play Game");
        playGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameButtonActionPerformed(evt);
            }
        });

        aboutGameButton.setBackground(new java.awt.Color(51, 51, 255));
        aboutGameButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutGameButton.setText("About Game");
        aboutGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutGameButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 102, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Player Name");

        playerNameTextField.setBackground(new java.awt.Color(102, 102, 255));
        playerNameTextField.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        player1jRadioButton.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(player1jRadioButton);
        player1jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1jRadioButtonActionPerformed(evt);
            }
        });

        player3jRadioButton.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(player3jRadioButton);
        player3jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3jRadioButtonActionPerformed(evt);
            }
        });

        player2jRadioButton.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(player2jRadioButton);
        player2jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2jRadioButtonActionPerformed(evt);
            }
        });

        player4jRadioButton.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(player4jRadioButton);
        player4jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4jRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player1jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(player3jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player3jRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player1jRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player4jRadioButton)
                            .addComponent(player2jRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player2jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(player4jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player2jRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player1jRadioButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(player1jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player2jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player3jRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player3jLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(player4jLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(player4jRadioButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerChoosedjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playerChoosedjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout homeGamePanelLayout = new javax.swing.GroupLayout(homeGamePanel);
        homeGamePanel.setLayout(homeGamePanelLayout);
        homeGamePanelLayout.setHorizontalGroup(
            homeGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeGamePanelLayout.setVerticalGroup(
            homeGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeGamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(null, "Exit !", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmation == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void aboutGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutGameButtonActionPerformed
        this.abgf = new AboutGameFrame();
        this.dispose();
        this.abgf.setVisible(true);
    }//GEN-LAST:event_aboutGameButtonActionPerformed

    private void playGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameButtonActionPerformed
        this.op = new OptionsFrame(this.playerNameTextField.getText(), this.playerImage);
        this.dispose();
        this.op.setVisible(true);
    }//GEN-LAST:event_playGameButtonActionPerformed

    private void player1jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1jRadioButtonActionPerformed
        if (this.buttonGroup1.isSelected(this.player1jRadioButton.getModel())) {
            this.playerImage = "images/player1.jpg";
            this.setAddPictureLabel(this.playerChoosedjLabel, this.getResizedImage(this.playerImage, this.playerChoosedjLabel.getWidth(), this.playerChoosedjLabel.getHeight()));
        }
    }//GEN-LAST:event_player1jRadioButtonActionPerformed

    private void player2jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2jRadioButtonActionPerformed
        if (this.buttonGroup1.isSelected(this.player2jRadioButton.getModel())) {
            this.playerImage = "images/player2.jpg";
            this.setAddPictureLabel(this.playerChoosedjLabel, this.getResizedImage(this.playerImage, this.playerChoosedjLabel.getWidth(), this.playerChoosedjLabel.getHeight()));
        }
    }//GEN-LAST:event_player2jRadioButtonActionPerformed

    private void player4jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4jRadioButtonActionPerformed
        if (this.buttonGroup1.isSelected(this.player4jRadioButton.getModel())) {
            this.playerImage = "images/player4.png";
            this.setAddPictureLabel(this.playerChoosedjLabel, this.getResizedImage(this.playerImage, this.playerChoosedjLabel.getWidth(), this.playerChoosedjLabel.getHeight()));
        }
    }//GEN-LAST:event_player4jRadioButtonActionPerformed

    private void player3jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3jRadioButtonActionPerformed
        if (this.buttonGroup1.isSelected(this.player3jRadioButton.getModel())) {
            this.playerImage = "images/player3.png";
            this.setAddPictureLabel(this.playerChoosedjLabel, this.getResizedImage(this.playerImage, this.playerChoosedjLabel.getWidth(), this.playerChoosedjLabel.getHeight()));
        }
    }//GEN-LAST:event_player3jRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutGameButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel homeGamePanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton playGameButton;
    private javax.swing.JLabel player1jLabel;
    private javax.swing.JRadioButton player1jRadioButton;
    private javax.swing.JLabel player2jLabel;
    private javax.swing.JRadioButton player2jRadioButton;
    private javax.swing.JLabel player3jLabel;
    private javax.swing.JRadioButton player3jRadioButton;
    private javax.swing.JLabel player4jLabel;
    private javax.swing.JRadioButton player4jRadioButton;
    private javax.swing.JLabel playerChoosedjLabel;
    private javax.swing.JTextField playerNameTextField;
    // End of variables declaration//GEN-END:variables
}
